language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage erase
  - coverage run runserver.py
after_success:
  - coveralls