language: python
services:
  - mysql
python:
  - "3.6"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage erase
  - coverage run runserver.py
after_success:
  - coveralls